ethstaker/ethstaker-deposit-cli

- .github/workflows/runner.yml
Our current runner matrix is missing a macOS amd64 only platform. The `macos-latest` is running on an M1 machine which might run on arm64 architecture. Adding `macos-12` should help improve our tests coverage.
The list of runners and images can be found on https://github.com/actions/runner-images
> Add macOS 12 runner for amd64 support on macOS

- .github/workflows/runner.yml
- staking_deposit/credentials.py
- staking_deposit/utils/ssz.py
- staking_deposit/utils/validation.py
Using the existing `flake8.ini` file.
`flake8 --config=flake8.ini ./staking_deposit ./tests` 
Looks like this was the setup for tox run by circleci
> Add linter step to github actions

- .github/workflows/runner.yml
Fixes #21 .
It seems like Github removed some support for older Python version on their runner. This will exclude it and fix our current failing runs.
> Exclude failing matrix job for macos-latest and Python 3.9

- staking_deposit/credentials.py
- staking_deposit/settings.py
Fixes #13 .
It adds support for [the Ephemery testnet](https://github.com/ephemery-testnet/ephemery-resources). It makes the GENESIS_VALIDATORS_ROOT value optional in the chain settings.
> Adding Ephemery testnet with optional GENESIS_VALIDATORS_ROOT

- staking_deposit/cli/generate_keys.py
- staking_deposit/cli/new_mnemonic.py
- staking_deposit/deposit.py
- staking_deposit/intl/en/cli/generate_keys.json
- staking_deposit/utils/click.py
- staking_deposit/utils/validation.py
- tests/test_cli/test_existing_mnemonic.py
- tests/test_cli/test_new_mnemonic.py
- tests/test_cli/test_regeneration.py
Adding a prompt for withdrawal address when executing key generation.  
There are a few changes of note:
- I have added a `default` param for the captive prompt. I simply don't see why not.
- I am not confirming selection if the user provides an empty value for the withdrawal address but we can add it if necessary
- `closest_match` in `intl.py` creates some pretty weird UX scenarios especially during language selection. As an example, if you provide `1234` as the option for language, it will chose `12`. My assumption this is used to avoid non-standard character match issues.
#16
> Withdrawal address prompt

- .github/workflows/build.yml
This PR adds 2 new elements to our build process with Github workflows:
1. It create PGP signatures based on the stored PGP private key with Github secrets. It expects 2 secrets: `GPG_PRIVATE_KEY` and `PASSPHRASE` as described with [the import-gpg action](https://github.com/marketplace/actions/import-gpg). I've already added those to the `eth-educators/ethstaker-deposit-cli` repo. You can see [the documentation](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions) on this for more details.
2. It creates build attestations to create a strong link between the workflow used to create the release assets and the eventual releases. See [the documentation](https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-buil …
> Add PGP signatures and attestations to build process

- README.md
- staking_deposit/cli/generate_keys.py
- staking_deposit/credentials.py
- staking_deposit/intl/en/cli/generate_keys.json
- tests/test_cli/test_existing_mnemonic.py
- tests/test_cli/test_exit_transaction_keystore.py
- tests/test_cli/test_new_mnemonic.py
Adding a flag that will allow keys to be generated using pbkdf2 derivation function instead of scrypt. This is a substantially faster alternative and good option for users if they were going to generate keys in bulk.
We will still default to scrypt but if the flag is specified, it will drill down to the key generation where either the existing `Pbkdf2Keystore` will be used or `ScryptKeystore` if not specified.
When it comes to exiting through the keystore file, there is no need to specify as the `Keystore.decrypt` function will call `self.kdf` which then does a simple check of `return scrypt(**kwargs) if 'scrypt' in self.crypto.kdf.function else PBKDF2(**kwargs)`
Fixes #37
> Pbkdf2 support

- staking_deposit/cli/exit_transaction_keystore.py
- staking_deposit/cli/exit_transaction_mnemonic.py
- staking_deposit/cli/generate_bls_to_execution_change.py
- staking_deposit/credentials.py
- staking_deposit/deposit.py
- staking_deposit/exit_transaction.py
- staking_deposit/intl/en/cli/exit_transaction_mnemonic.json
- staking_deposit/intl/en/cli/generate_bls_to_execution_change.json
- staking_deposit/utils/validation.py
- test_binary_btec_script.py
- test_binary_deposit_script.py
- test_btec_script.py
- test_deposit_script.py
- tests/test_cli/test_existing_mnemonic.py
- tests/test_cli/test_exit_transaction_mnemonic.py
- tests/test_cli/test_new_mnemonic.py
This PR adds parallelism using [the ProcessPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor) when and where we can benefit from executing multiple tasks on potentially multiple cores. This speeds up keys generation, keystores generation, voluntary exits generation and a bunch of verification especially when multiples are requested. It will default to using number of processors on the machine for the number of workers.
Fixes #40 
Introduces #47
> Add parallelism when performing multiple tasks at the same that can benefit from it

- staking_deposit/cli/exit_transaction_keystore.py
- staking_deposit/cli/exit_transaction_mnemonic.py
- staking_deposit/cli/generate_bls_to_execution_change.py
- staking_deposit/cli/generate_keys.py
- staking_deposit/settings.py
> Remove dead chains

- ethstaker_deposit/deposit.py
Instead of showing a massive stack trace for thrown errors, we will now wrap the `cli()` call and catch and `ValidatorError` or `ValueError` and then display what the error is.
To reproduce a stack traced ValidationError:
```
python3 -m ethstaker_deposit --non_interactive --language english existing-mnemonic --mnemonic="1234 4321 1234"
```
To reproduce a stack traced ValueError:
```
python3 -m ethstaker_deposit --language english --non_interactive generate-bls-to-execution-change --mnemonic="abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about" --chain="mainnet" --validator_start_index=0 --validator_indices="1 2" --bls_withdrawal_credentials_list=00245ac28e1ed7eb69d62af7bfbde0e154e749eaf80e208e947dde4c1ed236ad …
```
> Adding try/except when running cli to remove stack traces

- build_configs/common/requirements.txt
Fixes https://github.com/eth-educators/ethstaker-deposit-cli/security/dependabot/2
This dependency is only used during build. I started a new build process on https://github.com/remyroy/ethstaker-deposit-cli/actions/runs/9877400806 and everything was fine. After merging, we should start another build process on this repository to confirm.
> Update zipp package for security issue

- .github/workflows/docker.yml
- Dockerfile
Fixes #61
This PR slightly improves the current docker image and it creates a github workflow to build and publish the docker image on the github registry. The workflow is triggerd on pushing a tag that starts with `v`. It should be the convention when performing a release to add a related tag that starts with `v` and the version number.
An example of the result of this can be found on https://github.com/remyroy/ethstaker-deposit-cli/actions/runs/10013809719 . The related package can be found on https://github.com/remyroy/ethstaker-deposit-cli/pkgs/container/ethstaker-deposit-cli. Some of the related documentation can be found on https://docs.github.com/en/actions/publishing-packages/publishing-docker-images .
You can use this test docker image with something like:
```
docker pull …
```
> Add docker workflow and improve dockerfile

- ethstaker_deposit/cli/exit_transaction_keystore.py
- ethstaker_deposit/cli/exit_transaction_mnemonic.py
- ethstaker_deposit/cli/generate_keys.py
- ethstaker_deposit/credentials.py
- ethstaker_deposit/exit_transaction.py
- tests/test_cli/test_exit_transaction_keystore.py
Instead of generating a timestamp at the time of file creation, the value will be provided when files are created in bulk such as generating keys or exit transactions for mnemonics.
Fixes #35
> Share timestamp across generated files for an action

- .github/workflows/build.yml
It will result in sha256 filenames more in line with existing conventions in the ci-build process.
`ethstaker_deposit-cli-35351da-linux-amd64.tar.gz.sha256` instead of `ethstaker_deposit-cli-35351da-linux-amd64.sha256` for instance. See the assets produced on https://github.com/remyroy/ethstaker-deposit-cli/actions/runs/9877816858 compared to https://github.com/remyroy/ethstaker-deposit-cli/actions/runs/9877400806.
> Better name for build sha256 filenames

- .github/workflows/runner.yml
This is a workaround for #62 until I can find a better solution.
> Exclude Python 3.9 and macOS from CI matrix

- .github/workflows/build.yml
This should help with users who are on older linux OSes and those that are using an older version of glibc.
> Use an older version of Ubuntu for building to support users on older glibc versions

- .coveragerc
- .github/workflows/comment.yml
- .github/workflows/runner.yml
- .gitignore
Uses [coverage.py](https://coverage.readthedocs.io/en/7.6.1/) to produce coverage reports in CI.
Special care is given to avoid the security snafus in [this article](https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/)
`relative_files = True` is required for cross-platform compatibility when merging coverage reports generated by the run matrix.
An html report is generated and uploaded to github (retention 60 days), as well as a text summary.
The text summary and a link to the html report are added to the pull request as a comment.
Screenshots for reference:
NB: "comment" workflow file is added in a separate commit since it needs to reside on the target branch (see above link for security explanation)
> Add coverage reports to github actions

- .github/workflows/build.yml
- .github/workflows/runner.yml
Merge after the Python 3.13 runner is available. See also #74 
Changed `macos-12` to `macos-13` because of:
"While this release of 3.12 still supports them, it is likely that we will be forced to drop support for macOS 10.12 and older in a future 3.12 release. (Python 3.13 has already dropped support for them.)"
macOS is usually supported for 3 years, which means 12 would become unsupported when 15 releases, likely late October. https://endoflife.date/macos
> Python 3.13

- .github/workflows/runner.yml
- tests/test_cli/test_new_mnemonic.py
Instead of skipping all tests on macOS Python 3.9, skip just the ones that use asyncio PIPE
> Granular test skip on macOS Python 3.9

- README.md
Resolves #42 
Document `--keystore_password` in `README.md`. Dire warnings about history and `--non_interactive` have been included.
> Add `keystore_password` to `README.md`

- .github/CODEOWNERS
Create a `CODEOWNERS` file
This allow us in a future step to require review from a code owner, once we get to the more serious issues.
This is arguably a security feature as right now anyone in the org can do an approving review.
We may also want to look at who is admin and can change the protection settings.
> Establish Valefar and Remy as global code owners

- README.md
- docs/src/landing.md
Closes #54 
Document the canonical deposit contract address and launchpad URL for mainnet and Holesky
Also document binary creation for developers
`doctoc` has been run to update the ToC
> Document canonical deposit contract and launchpad

- .github/workflows/build.yml
- .github/workflows/runner.yml
Add custom ubuntu arm64 runners
Added a `run-tests` label. This way we can avoid running tests for documentation PRs or when a PR has been opened for code review and discussion and isn't ready for testing yet
Windows 11 ARM64 runners do not support Python at all presently. We can try again when they are out of beta at the end of the year.
> Arm64 runners

- ethstaker_deposit/deposit.py
Closes #106 
`./deposit command --help` will no longer check for Internet connectivity and warn. `./deposit command` will still check.
> Help with internet

- ethstaker_deposit/utils/click.py
- ethstaker_deposit/utils/constants.py
Closes #50 
This requires testing on multiple terminals. It won't look the same on all, particularly with spacing around the `,`, but it should look acceptable.
> RTL handling

- .pre-commit-config.yaml
- README.md
- docs/src/local_development.md
Add a pre-commit config and documentation. This allows devs to run `flake8` and `mypy` locally on commit, reducing iteration on a PR because of linter/typing failures
I have run `pre-commit run --all-files` and it passes
> Add pre-commit

- ethstaker_deposit/credentials.py
- ethstaker_deposit/deposit.py
- ethstaker_deposit/key_handling/key_derivation/mnemonic.py
- ethstaker_deposit/key_handling/key_derivation/path.py
- ethstaker_deposit/key_handling/key_derivation/tree.py
- ethstaker_deposit/utils/constants.py
- ethstaker_deposit/utils/intl.py
Python 3.9 introduced `list` type, no longer requiring `typing.List`. This PR changes all `List` to `list`, and removes the `typing.List` imports
> List becomes list

- ethstaker_deposit/deposit.py
- ethstaker_deposit/utils/click.py
Closes #19 
`--non_interactive` disables the `--language` prompt in the first top-level Click context
> Don't prompt for `--language` when `--non_interactive`

- ethstaker_deposit/deposit.py
- ethstaker_deposit/intl/en/utils/validation.json
- ethstaker_deposit/utils/validation.py
- tests/test_deposit.py
- tests/test_utils/test_validation.py
Resolves #34 
Checks for utf-8 terminal encoding on password strength check. If not `utf-8` and the password isn't ASCII, ask the user to retype.
If the platform is not Windows, suggest to switch to a `utf-8` terminal instead.
utf-8 terminal is not a standard on Windows, it uses "a zoo of code pages"
utf-8 console on Windows in Python is alas also not a thing. [PEP528](https://peps.python.org/pep-0528/) has been around since 2016, don't hold your breath.
The reason this failed in the Windows runner for staking-deposit-cli was that they checked only for `utf-8`, and Windows does not do `utf-8`.
> Check terminal encoding

- .github/workflows/comment.yml
- .github/workflows/runner.yml
First, update the main-branch task to implement what @yorickdowne attempted in https://github.com/eth-educators/ethstaker-deposit-cli/pull/128
Instead of skipping the comment job, it simply succeeds early:
Second, fix the data uploads which inexplicably stopped uploading hidden files without the `include-hidden-files` flag.
Finally, set `if-no-files-found: error` so that the test jobs fail if no coverage report is uploaded- otherwise, because the main-branch task fails open, we may see false negatives, which we really don't want.
A version bump for github-script is included out of fastidiousness.
> Fix coverage data uploads, update comment.yml workflow to fail open.

- ethstaker_deposit/cli/generate_bls_to_execution_change.py
- ethstaker_deposit/cli/generate_keys.py
- ethstaker_deposit/intl/en/utils/validation.json
- ethstaker_deposit/utils/constants.py
- ethstaker_deposit/utils/validation.py
- tests/test_cli/test_partial_deposit.py
- tests/test_utils/test_validation.py
Updating the `--amount` validation to no longer cap the value to what the smart contract supports (2**64 - 1) but to 2048 ether, a more realistic value
maintenance
I discussed with Remy and documentation will be handled in #140
> capping max deposit amount for partial to 2048

- docs/src/existing_mnemonic.md
- docs/src/generate_bls_to_execution_change.md
- docs/src/generate_bls_to_execution_change_keystore.md
- docs/src/landing.md
- docs/src/new_mnemonic.md
- ethstaker_deposit/bls_to_execution_change_keystore.py
- ethstaker_deposit/cli/generate_bls_to_execution_change_keystore.py
- ethstaker_deposit/credentials.py
- ethstaker_deposit/intl/en/cli/generate_bls_to_execution_change.json
- ethstaker_deposit/intl/en/cli/generate_bls_to_execution_change_keystore.json
- ethstaker_deposit/intl/en/cli/generate_keys.json
- ethstaker_deposit/intl/en/cli/partial_deposit.json
- ethstaker_deposit/intl/en/utils/validation.json
Fixes #133 
- Rework the documentation around the *execution address* to simplify it and mostly replace it with the *withdrawal address* term.
- Minor updates to code that still used the *execution address* term.
Documentation updates are included in this PR.
_If yes, fill in the details here. Remove if not applicable._
> Use withdrawal address instead of execution address and rework parts around it

- .github/workflows/build.yml
Fixes #152 
- Rework the build workflow to create assets with a different name on Ubuntu arm64 compared to Ubuntu amd64. See [a recent build run](https://github.com/eth-educators/ethstaker-deposit-cli/actions/runs/10887913346) to notice that they are currently both named `amd64`.
This will be tested during the next test release which should be in a few days.
> Use a different asset name for Ubuntu on arm64 binary assets

- docs/src/new_mnemonic.md
- ethstaker_deposit/cli/existing_mnemonic.py
- ethstaker_deposit/cli/new_mnemonic.py
- ethstaker_deposit/intl/en/cli/new_mnemonic.json
- pyproject.toml
- requirements.txt
Partially addresses #32  
Use `pyperclip`, which works on macOS, Linux and Windows, to set the clipboard to a space character after user is done inputting data
This introduces some host dependencies. Notably on Linux, clipboard mechanisms only exist if a window manager is present. So as to not bomb out on headless Linux, the code is in a `try: except:`
"On Windows, no additional modules are needed.
On Mac, this module makes use of the pbcopy and pbpaste commands, which should come with the os.
On Linux, this module makes use of the xclip or xsel commands, which should come with the os. Otherwise run “sudo apt-get install xclip” or “sudo apt-get install xsel” (Note: xsel does not always seem to work.)"
> Clear clipboard of the mnemonic

- ethstaker_deposit/cli/generate_bls_to_execution_change.py
- ethstaker_deposit/cli/generate_keys.py
- ethstaker_deposit/cli/new_mnemonic.py
- ethstaker_deposit/utils/terminal.py
- tests/test_cli/test_new_mnemonic.py
Resolves #32 , together with #130
Instead of `click.clear()` use `cls` or `tput reset`, depending on OS. This clears the scrollback of the terminal, at least on "modern" versions of Windows, Linux and macOS
> Clear scrollback

- ethstaker_deposit/utils/terminal.py
Fixes  #163 
Remove `LD_LIBRARY_PATH` for the call to `tput`, so system libraries are used. Otherwise, the bundled `libtinfo.so.6` can cause issues.
Note `libtinfo.so.6` was present all along, but only became an issue once we started calling `tput`
We will need to test the created binary on Ubuntu 20, 22, 24; Debian 11, 12. This is manual alas.
> Remove `LD_LIBRARY_PATH` on Linux when calling `tput`

- ethstaker_deposit/utils/terminal.py
Create `clean_env` on macOS so the subprocess.call works
> Fix mac clear

- docs/src/SUMMARY.md
- docs/src/bls_to_execution_change_file.md
- docs/src/generate_bls_to_execution_change.md
**What I did**
Added a page for the BLS to execution change file file format in the documentation.
Part of #167 and #148
> Add documentation page for BLS to execution change file

- docs/src/SUMMARY.md
- docs/src/release_process.md
Part of #26 . Also fixes #26 
- Document the release process with step by step instructions for anyone to be able to release a new version of [ethstaker-deposit-cli](https://github.com/eth-educators/ethstaker-deposit-cli).
This will be tested with the next test release to be created in the new few days.
This is the documentation update.
This is mostly internal documentation.
> Add release instructions

- docs/src/SUMMARY.md
- docs/src/bls_to_execution_change_file.md
- docs/src/exit_transaction_keystore.md
- docs/src/exit_transaction_mnemonic.md
- docs/src/generate_bls_to_execution_change.md
- docs/src/signed_exit_transaction_file.md
**What I did**
Added a documentation page for the Signed Exit Transaction file format. Also fixed some minor documentation issues.
Part of #167 and #148
> Add documentation page for Signed Exit Transaction file and related fixes

- ethstaker_deposit/cli/exit_transaction_keystore.py
- ethstaker_deposit/cli/generate_bls_to_execution_change_keystore.py
- ethstaker_deposit/cli/partial_deposit.py
- ethstaker_deposit/cli/test_keystore.py
**What I did**
Replaced usages of `exit` with `sys.exit` as was the case in `deposit.py`
FIxes #175
> Use sys.exit instead of exit

- docs/src/generate_bls_to_execution_change_keystore.md
- docs/src/quick_setup.md
**What I did**
There was missing or incorrect documentation with the `generate-bls-to-execution-change-keystore` command that caused confusion.
> Adding missing bls_keystore documentation

- ethstaker_deposit/utils/terminal.py
**What I did**
Changed the terminal clear logic to use all methods as suggested by ToB during the call. 
Two things to note:
- I noticed no benefit between this versus changing the ordering. With this change, there is a noticeable lag when clearing the terminal. Unless we have a use case for this I would rather change ordering as originally suggestetd.
- When a clear is attempted in iterm2, it does not happen automatically. Instead the user is shown a warning which can easily be ignored. I'm not aware of any 
way to bypass this.
Fixes #186
> bugfix: Use all clearing methods for linux/darwin

- .github/workflows/build.yml
**What I did**
Removed the use of eval in our build workflow. It is not needed.
Part of the fixes for #187 .
> Remove the use of eval in build workflow

- Dockerfile
**What I did**
Pinned dockerfile image with sha256 hash. You can compare it with what's available on the hub at https://hub.docker.com/layers/library/python/3.12-slim-bookworm/images/sha256-d2ead4f6f2ac4b88e44b45a06caea68ad3e2280c0028afcf136e9edfe28c2346?context=explore
Part of the fix to #181
> Pin dockerfile image with sha256 hash

- ethstaker_deposit/utils/click.py
**What I did**
Removed the return call in `JITOption.__init__`. It is not needed and it should not be there.
Part of the fixes for #187.
> Don't return in `JITOption.__init__`

- .github/workflows/comment.yml
**What I did**
I changed how the comment workflow works to check for the success of the coverage-combine job on the ci-runner workflow.
Fixes #156
> Fix the comment workflow failure by checking for the coverage job success

- .github/workflows/runner.yml
- docs/src/local_development.md
**What I did**
Improved runner workflow and minor fixes for shell scripts
This is somewhat needed by the fact that dependabot is removing `-r requirements.txt` from our `requirements_test.txt` file when updating dependencies.
Part of the fixes for #187 with shellcheck tool recommendations.
> Improved runner workflow and minor fixes for shell scripts

- ethstaker_deposit/bls_to_execution_change_keystore.py
- ethstaker_deposit/credentials.py
- ethstaker_deposit/key_handling/keystore.py
- ethstaker_deposit/utils/deposit.py
- ethstaker_deposit/utils/exit_transaction.py
- ethstaker_deposit/utils/file_handling.py
- tests/test_cli/helpers.py
- tests/test_cli/test_existing_mnemonic.py
- tests/test_cli/test_new_mnemonic.py
- tests/test_cli/test_partial_deposit.py
- tests/test_cli/test_regeneration.py
**What I did**
I created a `sensitive_opener` to be used with the open built-in function to ensure that newly create sensitives files were using the 400 permissions with the O_EXCL flag set.
Fixes #183
> Use 400 for sensitive files permissions on creation with O_EXCL flag

- ethstaker_deposit/bls_to_execution_change_keystore.py
- ethstaker_deposit/credentials.py
- ethstaker_deposit/key_handling/keystore.py
- ethstaker_deposit/utils/deposit.py
- ethstaker_deposit/utils/exit_transaction.py
- tests/test_cli/test_partial_deposit.py
**What I did**
Modified all our open built-in function call to use utf-8 as the encoding since we are just writing and reading JSON files.
Part of the fixes for #187 . Depends and builds on top of #208 .
> Use utf-8 encoding for all JSON file writing and reading

- .github/workflows/runner.yml
- Makefile
- build_configs/windows/requirements.in
- build_configs/windows/requirements.txt
- docs/src/local_development.md
- pyproject.toml
- requirements.txt
- requirements_test.in
- requirements_test.txt
- uv.lock
**What I did**
The colorama package is only needed by click on Windows. It should be in `requirements.txt` as a platform dependent dependency just like it is [in click](https://github.com/pallets/click/blob/main/pyproject.toml#L18).
This is related to the dependabot PRs and [the test failures](https://github.com/eth-educators/ethstaker-deposit-cli/actions/runs/11462141972/job/31892887693?pr=202) we are seeing on one of them. It should help with using dependabot to manage our dependencies.
> Moved colorama dependency to platform dependent in requirements.txt

- Dockerfile
**What I did**
I updated the docker python image we are using to the pinned version of python:3.12.7-slim-bookworm . See https://hub.docker.com/_/python/tags?name=3.12.7-slim-bookworm to confirm the digest SHA256.
> Bump python docker image to python:3.12.7-slim-bookworm

- docs/src/deposit_data_file.md
- ethstaker_deposit/cli/partial_deposit.py
- ethstaker_deposit/credentials.py
- ethstaker_deposit/settings.py
**What I did**
I'm modifying the version number we are using for the `deposit_cli_version` field in the deposit data files we are producing. I'm adding 10 to our major version number to make it large enough to pass the current Launchpad test in regards with this.
Related to #216 . It doesn't entirely fix that issue, but it's a short term solution that works for now.
> Use a fake version value for the deposit data file to work around a Launchpad issue

- docs/src/existing_mnemonic.md
- docs/src/exit_transaction_keystore.md
- docs/src/exit_transaction_mnemonic.md
- docs/src/generate_bls_to_execution_change.md
- docs/src/generate_bls_to_execution_change_keystore.md
- docs/src/new_mnemonic.md
- docs/src/partial_deposit.md
- ethstaker_deposit/settings.py
**What I did**
Added the Mekong testnet settings so it can be used as any other supported testnet with his name without having to manually use the `--devnet_chain_setting` flag.
You can find and confirm these settings on https://mekong.ethpandaops.io/.
- Genesis fork version: https://github.com/ethpandaops/mekong-devnets/blob/master/network-configs/devnet-0/metadata/config.yaml
- Exit fork version: https://github.com/ethpandaops/mekong-devnets/blob/master/network-configs/devnet-0/metadata/config.yaml
- Genesis validators root: https://github.com/ethpandaops/mekong-devnets/blob/master/network-configs/devnet-0/metadata/genesis_validators_root.txt
> Adding the Mekong testnet settings as another supported testnet

- docs/src/bls_to_execution_change_file.md
- docs/src/quick_setup.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "loosly" to "loosely".
Corrected "right clicking" to "right-clicking".
Corrected "suites" to "suits".
Please review the changes and let me know if any additional changes are needed.
> fix: typos in documentation files

- ethstaker_deposit/cli/exit_transaction_mnemonic.py
- ethstaker_deposit/utils/terminal.py
- uv.lock
The scrollback history on iTerm2 is only cleared when calling clear twice. This should fixed the issue.
Fixes #186
> Call everything in clear terminal twice

- docs/src/existing_mnemonic.md
- docs/src/exit_transaction_keystore.md
- docs/src/exit_transaction_mnemonic.md
- docs/src/generate_bls_to_execution_change.md
- docs/src/generate_bls_to_execution_change_keystore.md
- docs/src/new_mnemonic.md
- docs/src/partial_deposit.md
- ethstaker_deposit/settings.py
**What I did**
I added Gnosis Chain and Chiado (the Gnosis Chain testnet) to the compatible networks.
**Future changes**
If we can do it in an elegant way, we'd also love to create a separate PR to update the `--amount` argument, as Gnosis Chain has the minimum set to 1 GNO and the maximum to 64 GNO, so the same as Ethereum but divided by 32. This would be ideal in order not to confuse our users.
> feat: add Gnosis and Chiado

- .github/workflows/build.yml
- .github/workflows/runner.yml
**What I did**
Switched us to public Linux ARM runners
See https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
**(not mandatory) A picture of a cute animal, if possible in relation to what you did**
> Switch to public Linux arm runners

- .github/workflows/build.yml
**What I did**
Remove riscv64 from multi-arch Docker build, as that step fails because there's no Python
> buildx cannot build on riscv64, no Python

- Dockerfile
**What I did**
Dockerfile uses the sha256 for Python 3.13.2 slim-bookworm
Small dependency maintenance
> Bump Dockerfile to Python 3.13.2

- .github/workflows/build.yml
**What I did**
I updated Ubuntu runner image from 20.04 to 22.04. The 20.04 image will become unsupported on April 1 with a brownout period starting on March 4.
This is related to this announcement: https://github.com/actions/runner-images/issues/11101
> Update Ubuntu runner image to 22.04

- docs/src/deposit_data_file.md
Fixed **"loosly"** → **"loosely"** for accuracy and readability.
> Typo in thedeposit_data_file.md

- README.md
- docs/src/existing_mnemonic.md
- docs/src/exit_transaction_keystore.md
- docs/src/exit_transaction_mnemonic.md
- docs/src/generate_bls_to_execution_change.md
- docs/src/generate_bls_to_execution_change_keystore.md
- docs/src/new_mnemonic.md
- docs/src/partial_deposit.md
- ethstaker_deposit/settings.py
**What I did**
This is in relation with the recent deprecation of Mekong and the new Hoodi testnet to replace Holesky.
See:
- https://github.com/eth-clients/hoodi
> Removing Mekong and adding Hoodi testnets

- ethstaker_deposit/cli/generate_keys.py
**What I did**
Use `no` as the default value for the compounding flag/question. Improve the shown default in `--help` call.
Fixes #292
> Use better default for compounding flag

- .github/workflows/build.yml
- .github/workflows/runner.yml
Add Windows 11 ARM64 to CI and build workflow
> Add Windows 11 ARM64 to workflows

- pyproject.toml
**What I did**
Dynamically find packages so we don't just have `ethstaker_deposit` top level, but also everything below it that has an `__init__.py`. This allows users to use it in `requirements.txt` thusly:
```
ethstaker-deposit @ git+https://github.com/eth-educators/ethstaker-deposit-cli@v1.3.0
```
(Assuming 1.3.0 has this fix in it)
Closes #286 
**(not mandatory) A picture of a cute animal, if possible in relation to what you did**
> Fix packaging for use as a library

- .github/dependabot.yml
**What I did**
Group dependabot for everything. This means we need to run fewer CI tests, and have fewer PRs to review and accept. Also, the CI will catch any interactions between updates that might break something
I kept pydantic in its own group because it tends to break with pydantic-core: This way we can specifically exclude a pydantic-core version there, without touching any other dependencies. This is definitely a compromise.
dependabot will add a dependency to the first matching group. This will not include pydantic* twice
> Group all dependabot PRs

- ethstaker_deposit/intl/en/cli/partial_deposit.json
It turns out there's a missing partial_deposit/arg_withdrawal_address/mismatch text. If the lambda at `ethstaker_deposit/cli/partial_deposit.py:118` is called, an exception is thrown.
```python
@jit_option(
callback=captive_prompt_callback(
lambda address, _: validate_withdrawal_address(None, None, address, True),
lambda: load_text(['arg_withdrawal_address', 'prompt'], func=FUNC_NAME),
lambda: load_text(['arg_withdrawal_address', 'confirm'], func=FUNC_NAME),
HERE--> lambda: load_text(['arg_withdrawal_address', 'mismatch'], func=FUNC_NAME),
prompt_if=prompt_if_none,
),
help=lambda: load_text(['arg_withdrawal_address', 'help'], func=FUNC_NAME),
param_decls=['--withdrawal_address', '--execution_address', '--eth1_withdrawal_credentials'],
prompt=False,  # the callback handles the prompt
)
``` …
> add missing partial_deposit/arg_withdrawal_address/mismatch text

- ethstaker_deposit/cli/partial_deposit.py
- ethstaker_deposit/intl/en/cli/partial_deposit.json
- tests/test_cli/test_partial_deposit.py
**What I did**
For compatibility, added the existing amount calculation logic to partial deposit flow
**(not mandatory) A picture of a cute animal, if possible in relation to what you did**
> feat: make amount contextful on partial deposit

- docs/src/bls_to_execution_change_file.md
- docs/src/deposit_data_file.md
- docs/src/existing_mnemonic.md
- docs/src/exit_transaction_keystore.md
- docs/src/exit_transaction_mnemonic.md
- docs/src/generate_bls_to_execution_change.md
- docs/src/generate_bls_to_execution_change_keystore.md
- docs/src/new_mnemonic.md
- docs/src/other_install_options.md
- docs/src/partial_deposit.md
- ethstaker_deposit/settings.py
- tests/test_cli/test_existing_mnemonic.py
- tests/test_cli/test_exit_transaction_keystore.py
- tests/test_cli/test_exit_transaction_mnemonic.py
- tests/test_cli/test_generate_bls_to_execution_change.py
- tests/test_cli/test_generate_bls_to_execution_change_keystore.py
- tests/test_cli/test_new_mnemonic.py
- tests/test_cli/test_partial_deposit.py
- tests/test_utils/test_validation.py
**What I did**
Remove support for Holesky network. Change all tests to use Hoodi and copies of Hoodi
Hoodi parameters are at https://github.com/eth-clients/hoodi
> Remove Holesky, replace with Hoodi

- .github/workflows/build.yml
- .github/workflows/runner.yml
**What I did**
Replace `macos-13` with `macos-15-intel`
https://github.com/actions/runner-images/issues/13045
We will discontinue macOS x64 support no later than August 2027, and our next release should mention that in release notes
"GitHub Actions is starting the deprecation process for macOS 13 and macOS 13 arm64. For users that require the x86_64 (Intel) environment, we are introducing a new label to migrate to: macos-15-intel. The new label will run on macOS 15 and will be available from now until August 2027. This will be the last available x86_64 image from Actions, and after that date the x86_64 architecture will not be supported on GitHub Actions."
> Use macos15-intel for macOS x64 build

- .github/dependabot.yml
**What I did**
Teach dependabot to update `uv.lock`
We never had an `npm` run because we don't use `npm`, remove that section
> Dependabot updates uv
