ethstaker/ethstaker-deposit-cli

ethstaker_deposit/key_handling/key_derivation/mnemonic.py, ethstaker_deposit/utils/intl.py, ethstaker_deposit/utils/validation.py
Fixes #64 and improves the results from running [bandit](https://bandit.readthedocs.io/)
=> Replace asserts with raising a ValidatorError

ethstaker_deposit/utils/click.py
=> Fix for issue with dynamic default in captive prompt

ethstaker_deposit/deposit.py
=> Order click commands

ethstaker_deposit/intl/en/cli/generate_keys.json
Fixes #51 
`mnemonic` becomes `password` in help
=> Fix misleading help message

ethstaker_deposit/intl/en/cli/existing_mnemonic.json
Closes #52 
Clarify which index is meant during confirmation
=> Clarify confirmation prompt

ethstaker_deposit/credentials.py, ethstaker_deposit/key_handling/key_derivation/mnemonic.py, ethstaker_deposit/key_handling/key_derivation/tree.py, ethstaker_deposit/key_handling/keystore.py, ethstaker_deposit/utils/click.py, ethstaker_deposit/utils/crypto.py, ethstaker_deposit/utils/intl.py, flake8.ini
No longer ignore flake8 `E252` and `W504`
=> Remove linter ignores

.github/workflows/runner.yml
Closes #122 
`runner.yml` will lint and type check first, and only run tests if this is successful
- Fail fast on flake8 / mypy errors
- Don't churn through runner minutes if a PR was opened without pre-commit
=> Lint first

.github/workflows/runner.yml, .pre-commit-config.yaml
Add a JSON linter to `pre-commit` and Github action
No changes to `flake8` and `mypy` in this. A second PR might offer running `super-linter` instead of individual lint tools.
=> Lint JSON files

uv.lock
Add a `uv.lock` file. No other changes.
=> Support `uv`

docs/src/CNAME
Closes #125 
Add `deposit-cli.ethstaker.cc` as the CNAME for the GH pages deployment of our docs
=> Add a CNAME to gh pages

.github/workflows/runner.yml
=> Python 3.13.0-rc2 for now

docs/src/SUMMARY.md, docs/src/deposit_data_file.md, docs/src/existing_mnemonic.md, docs/src/keystore_file.md, docs/src/new_mnemonic.md, docs/src/partial_deposit.md
Fixes #140
Added 2 pages in the documentation for the keystore and deposit data file. Reworked documentation for these new pages.
=> Add documentation for keystore and deposit data files

.github/workflows/build.yml
Fixes #153 
Related to #26 
- Trigger build workflow on tag starting with a `v` added to the repo.
This will be tested during the next test release which should be in a few days.
Eventually, this will have to be updated in a branch I'm working on for the release process.
=> Start build workflow on tag

docs/src/local_development.md
Document Windows prerequisites for a dev machine
=> Notes on Windows prerequisites

docs/src/SUMMARY.md, docs/src/bls_to_execution_change_keystore_file.md, docs/src/generate_bls_to_execution_change_keystore.md
**What I did**
Added references to `bls-to-execution-change-keystore` docs that already existed and added some more about file format
#167
=> Adding documentation for bls-to-execution-change-keystore command

.github/workflows/runner.yml
**What I did**
Move to Python 3.13 from 3.13.0-rc.2
=> Switch to Python 3.13 stable

docs/src/SUMMARY.md, docs/src/reporting_vulnerability.md
**What I did**
Added documentation page for reporting a vulnerability
Somewhat depends on #191 .
=> Added documentation page for reporting a vulnerability

.github/workflows/runner.yml
**What I did**
Pinned the jsonlint tool in our lint job.
Part of the fixes for #187 .
=> Pin jsonlint tool

.github/workflows/docker.yml, .github/workflows/docs.yml
**What I did**
Pinned third party workflow actions for security.
Part of the fixes for #181 .
=> Pinned third party workflow actions

ethstaker_deposit/cli/existing_mnemonic.py, ethstaker_deposit/cli/new_mnemonic.py, ethstaker_deposit/intl/en/cli/existing_mnemonic.json, ethstaker_deposit/intl/en/cli/new_mnemonic.json, tests/test_cli/test_existing_mnemonic.py, tests/test_cli/test_new_mnemonic.py, tests/test_cli/test_regeneration.py, tests/test_deposit.py
**What I did**
I added a warning message about the clipboard being cleared while showing the mnemonic and during the retyping confirmation. I added a prompt with a press for any key before clearing the clipboard with a warning message about it.
Fixes #185
=> Emphasize clipboard clearing warning

ethstaker_deposit/utils/intl.py
**What I did**
I modified the logic to find the relative path to the i18n JSON file from using the first occurence of the project directory name in the path list to the last one.
Fixes #184 .
=> Use a relative path from the last occurence of the project directory name

docs/src/existing_mnemonic.md, docs/src/new_mnemonic.md, docs/src/partial_deposit.md
**What I did**
Adding a bit more explanation on how to create a non-32 ETH deposit
fixes #218
=> Adding documentation how to create a non-32 eth deposit

README.md, SECURITY.md, docs/src/landing.md
**What I did**
I added the published security report links with some details in preparation for the full version 1.0 release.
=> Add security report details

Dockerfile
**What I did**
Revert Docker Python image to version 3.12.
Fixes #281
=> Fix Dockerfile with previous Python image version

README.md
**What I did**
I removed the Holesky network and I added the Gnosis networks details from the README file.
=> Add Gnosis networks and remove Holesky in README file

docs/src/landing.md
**What I did**
Our README file has an updated section for deposit addresses and launchpad address. This updates the same section in our documentation.
=> Update documentation deposit section
